// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © ej28power

//@version=6
indicator("Power BB MA", shorttitle="Power BB MA", overlay=true)

// 볼린저밴드
length = input.int(20, minval=1, title="Length") // 20일선
mult = input.float(2.0, title="StdDev Multiplier")

sma = ta.sma(close, length)
dev = mult * ta.stdev(close, length)
upper = sma + dev
lower = sma - dev

bb_middle = plot(sma, color=color.new(color.red, 0), style = plot.style_line, linewidth=4, title="Middle Band")
bb_upper = plot(upper, color=color.new(color.blue, 0), style = plot.style_line, linewidth=1, title="Upper Band")
bb_lower = plot(lower, color=color.new(color.blue, 0), style = plot.style_line, linewidth=1, title="Lower Band")

myBBColor = color.new(color.blue, 80)
fill(bb_upper, bb_lower, myBBColor)

// EMA
val_01 = input.int(35, title="35")
val_02 = input.int(50, title="50")
val_03 = input.int(65, title="65")
val_04 = input.int(100, title="100")
val_05 = input.int(200, title="200")
val_06 = input.int(300, title="300")

ema_01 = plot(ta.ema(close, val_01), color=color.new(color.orange, 0), style = plot.style_line, linewidth = 2, title="EMA_35")
ema_02 = plot(ta.ema(close, val_02), color=color.new(color.yellow, 0), style = plot.style_line, linewidth = 2, title="EMA_50")
ema_03 = plot(ta.ema(close, val_03), color=color.new(color.green, 0), style = plot.style_line, linewidth = 2, title="EMA_65")
ema_04 = plot(ta.ema(close, val_04), color=color.new(color.black, 0), style = plot.style_line, linewidth = 2, title="EMA_100")
ema_05 = plot(ta.ema(close, val_05), color=color.new(color.black, 0), style = plot.style_line, linewidth = 4, title="EMA_200")
ema_06 = plot(ta.ema(close, val_06), color=color.new(color.black, 0), style = plot.style_line, linewidth = 2, title="EMA_300")

long_position_01 = false
short_position_01 = false
myColor = color.new(color.black, 100)
if ta.ema(close, val_04) > ta.ema(close, val_06)
    myColor := color.new(color.green, 80)
    long_position_01 := true
else
    myColor := color.new(color.red, 80)
    short_position_01 := true
fill(ema_04, ema_06, myColor)

long_position_02 = ta.crossover(ta.ema(close, val_04), ta.ema(close, val_06))
short_position_02 = ta.crossunder(ta.ema(close, val_04), ta.ema(close, val_06))

if long_position_02 and long_position_01
    line.new(bar_index, close, bar_index, close * 0.01, color = color.new(color.blue, 50), style = line.style_dashed, width = 1, extend = extend.both)
    line.new(bar_index + 1, close, bar_index + 51, close, color = color.new(color.blue, 50), style = line.style_solid, width = 1, extend = extend.none)
    label.new(x=bar_index + 1, y=close, color=color.blue, textcolor=color.white, style=label.style_label_left, size=size.small, text = "롱 " + str.tostring(close))

else if short_position_02 and short_position_01
    line.new(bar_index, close, bar_index, close * 0.01, color = color.new(color.orange, 50), style = line.style_dashed, width = 1, extend = extend.both)
    line.new(bar_index + 1, close, bar_index + 51, close, color = color.new(color.orange, 50), style = line.style_solid, width = 1, extend = extend.none)
    label.new(x=bar_index + 1, y=close, color=color.orange, textcolor=color.white, style=label.style_label_left, size=size.small, text = "숏 " + str.tostring(close))
